# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Fir
site_url: https://daelvn.github.io/fir

repo_url: https://github.com/daelvn/fir
repo_name: daelvn/fir

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {}
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  palette: 
    primary: custom
  icon:
    logo: material/pine-tree
  features:
    - navigation.tabs
    - navigation.indexes
    - content.tabs.link
