---# Tests for examples.module #---
-- This test suite was automatically generated from documentation comments,
-- the tests are embedded in the code itself. Do not edit this file.
local assert = require('luassert')
local M = require('examples.module')

local field = M['field'] -- field

local args, tags = {...}, {}
for _, v in ipairs(args) do tags[v] = true end

print 'General ->'

print '  Tests ->'


print '    field#1'
assert.equals(4, field)
